<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<RootNamespace>MazePhysicsGame</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Assets\*.png" />
	</ItemGroup>
</Project>